name: setup node
description: "set up node.js, cache dependencies and install dependencies"

runs:
  using: "composite"
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install
