name: publish to github page
description: ""

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  cancel-in-progress: false
  group: "pages"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-node

      - uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
